#!/usr/bin/env python3
"""
train_endgame.py -- Supervised endgame training pass for the AlphaZero chess network.

Why this exists: the main stockfish_train.py loop generates games at 1320 Elo, which
rarely reaches clean endgames. The value head therefore gets almost no signal for
"king + queen vs king = won" vs "drawn position", causing the model to fail to convert
winning endgames and occasionally lose drawn ones.

KEY DESIGN PRINCIPLE -- color balance:
  Every endgame type is generated in ALL FOUR color/turn combinations:
    1. White-up, White-to-move   (theoretical: "win")
    2. Black-up, Black-to-move   (theoretical: "win")
    3. White-up, Black-to-move   (theoretical: "loss" -- defender to move)
    4. Black-up, White-to-move   (theoretical: "loss" -- defender to move)

  Cases 1 & 2 are produced by board.mirror(). Cases 3 & 4 flip the turn on
  each board so the material-DOWN side moves first. This is critical: without
  cases 3 & 4, every game starts with the attacker moving, defender plies
  always produce z=-1, and the value head collapses to always predicting -1.

  The theoretical outcome label is always expressed from the perspective of the
  SIDE TO MOVE at the start of the position:
    "win"  = the side to move should win with best play
    "draw" = the position is a theoretical draw with best play
    "loss" = the side to move should lose with best play (defender-to-move cases)
  This means z targets will be naturally balanced (+1 / 0 / -1) rather than
  skewed toward any one color.

Bonus/penalty weight hierarchy (applied to loss scaling, not value targets):
  - Lose a winning endgame:  -1.0  (heaviest -- this is the core bug to fix)
  - Draw a winning endgame:  -0.5  (moderate -- failed to convert a won position)
  - Win a winning endgame:   +0.8  (strong -- reinforce correct conversion)
  - Lose a drawn endgame:    -0.3  (light -- shouldn't lose but opponent didn't blunder)
  - Draw a drawn endgame:     0.0  (correct outcome -- no extra signal needed)
  - Win a drawn endgame:     +0.15 (very light -- opponent blundered, don't overfit)

Sign convention: value targets z are ALWAYS from the side-to-move's perspective,
matching train.py and stockfish_train.py exactly. Do not change this.

Usage:
    python3 train_endgame.py --model best_model.pt --stockfish-dir stockfish \\
        --device mps --positions 1000 --train-steps 50

    # Re-run whenever check_value_head.py shows regression
"""

import argparse
import glob
import logging
import os
import platform
import random
import stat

import chess
import chess.engine
import numpy as np
import torch
import torch.nn.functional as F
from tqdm import tqdm

import train  # reuse DualHeadResNet, board_to_tensor, move_policy_index exactly

log = logging.getLogger("train_endgame")


# ---------------------------------------------------------------------------
# Outcome weights.
# theoretical: "win" = side-to-move should win, "draw" = theoretical draw.
# actual:      "win" / "draw" / "loss" from side-to-move's perspective.
# ---------------------------------------------------------------------------
OUTCOME_WEIGHTS = {
    ("win",  "win"):   0.8,   # converted a winning endgame -- strong positive
    ("win",  "draw"): -0.5,   # failed to convert a won position -- moderate penalty
    ("win",  "loss"): -1.0,   # lost a winning endgame -- heaviest penalty (core bug)
    ("draw", "win"):   0.15,  # won a drawn endgame -- opponent blundered, tiny bonus
    ("draw", "draw"):  0.0,   # correctly held the draw -- neutral
    ("draw", "loss"): -0.3,   # lost a drawn endgame -- light penalty
    # Defender-to-move positions (generated by _both_colors cases 3 & 4):
    # theoretical="loss" means the side to move is the material-DOWN defender.
    ("loss", "loss"):  0.8,   # correctly lost as the defender -- strong positive
    ("loss", "draw"):  0.3,   # held a draw as the defender -- mild positive (stubborn defence)
    ("loss", "win"):  -0.5,   # won as the defender -- attacker blundered badly
}

BASE_WEIGHT = 0.3  # minimum loss weight so neutral examples still contribute


# ---------------------------------------------------------------------------
# Position generation helpers
# ---------------------------------------------------------------------------

def _random_square(exclude=None):
    exclude = set(exclude or [])
    sq = random.randint(0, 63)
    while sq in exclude:
        sq = random.randint(0, 63)
    return sq


def _kings_too_close(sq1, sq2, min_dist=2):
    r1, c1 = divmod(sq1, 8)
    r2, c2 = divmod(sq2, 8)
    return max(abs(r1 - r2), abs(c1 - c2)) < min_dist


def _make_board(*pieces):
    """
    Build a board from a list of (square, Piece) tuples.
    Always sets White to move, clears castling and en passant.
    Returns None if the position is invalid, checkmate, or stalemate.
    """
    board = chess.Board(fen=None)
    for sq, piece in pieces:
        board.set_piece_at(sq, piece)
    board.turn = chess.WHITE
    board.castling_rights = chess.BB_EMPTY
    board.ep_square = None
    if not board.is_valid():
        return None
    if board.is_checkmate() or board.is_stalemate():
        return None
    return board


def _both_colors(board, theoretical_stm):
    """
    Given a White-up, White-to-move board, return FOUR (board, theoretical_from_stm)
    pairs covering all combinations of which color holds the material advantage and
    which color is to move:

      1. White-up, White-to-move  (original)           theoretical = theoretical_stm ("win")
      2. Black-up, Black-to-move  (mirror of original)  theoretical = theoretical_stm ("win")
      3. White-up, Black-to-move  (original, turn flipped) theoretical = "loss"
         (Black is to move but White has the material -- Black should lose)
      4. Black-up, White-to-move  (mirror, turn flipped)   theoretical = "loss"
         (White is to move but Black has the material -- White should lose)

    Cases 3 & 4 were missing before: every generated game started with the
    material-up side to move, so defender plies always produced z=-1, flooding
    the value head with "mover loses" signal and causing collapse to -1.

    Note: flipping the turn on an already-built board is safe here because
    _make_board has already validated legality with White to move. We re-check
    for immediate checkmate/stalemate after flipping.
    """
    results = []

    # Cases 1 & 2: material-up side to move (original behaviour)
    mirrored = board.mirror()
    results.append((board, theoretical_stm))
    results.append((mirrored, theoretical_stm))

    # Cases 3 & 4: defender to move -- flip turn on each board
    for b in (board, mirrored):
        b2 = b.copy()
        b2.turn = not b2.turn  # give the move to the material-DOWN side
        if b2.is_valid() and not b2.is_checkmate() and not b2.is_stalemate():
            # theoretical from the new side-to-move's perspective: they are losing
            results.append((b2, "loss"))

    return results


# ---------------------------------------------------------------------------
# Endgame position generators
# Each generator produces n positions total across all four combinations:
#   attacker-to-move (White-up/White, Black-up/Black) and
#   defender-to-move (White-up/Black, Black-up/White).
# theoretical outcome is ALWAYS from the side-to-move's perspective.
# ---------------------------------------------------------------------------

def gen_kqk(n):
    """KQK: the side to move has K+Q, opponent has only K. Theoretical win."""
    positions = []
    attempts = 0
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        wk = _random_square()
        bk = _random_square(exclude=[wk])
        if _kings_too_close(wk, bk, min_dist=2):
            continue
        wq = _random_square(exclude=[wk, bk])
        board = _make_board(
            (wk, chess.Piece(chess.KING, chess.WHITE)),
            (bk, chess.Piece(chess.KING, chess.BLACK)),
            (wq, chess.Piece(chess.QUEEN, chess.WHITE)),
        )
        if board is None:
            continue
        for b, t in _both_colors(board, "win"):
            positions.append((b, t))
            if len(positions) >= n:
                break
    return positions[:n]


def gen_krk(n):
    """KRK: the side to move has K+R, opponent has only K. Theoretical win."""
    positions = []
    attempts = 0
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        wk = _random_square()
        bk = _random_square(exclude=[wk])
        if _kings_too_close(wk, bk, min_dist=2):
            continue
        wr = _random_square(exclude=[wk, bk])
        board = _make_board(
            (wk, chess.Piece(chess.KING, chess.WHITE)),
            (bk, chess.Piece(chess.KING, chess.BLACK)),
            (wr, chess.Piece(chess.ROOK, chess.WHITE)),
        )
        if board is None:
            continue
        for b, t in _both_colors(board, "win"):
            positions.append((b, t))
            if len(positions) >= n:
                break
    return positions[:n]


def gen_kpk(n):
    """KPK: the side to move has K+P, opponent has only K.
    Labelled as theoretical 'win' -- OUTCOME_WEIGHTS will handle the drawn
    cases (e.g. blocked rook pawn) via the play-out result."""
    positions = []
    attempts = 0
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        pawn_file = random.randint(0, 7)
        pawn_rank = random.randint(1, 5)  # ranks 1-5 (0-indexed), not 0 or 6/7
        wp = chess.square(pawn_file, pawn_rank)
        wk = _random_square(exclude=[wp])
        bk = _random_square(exclude=[wp, wk])
        if _kings_too_close(wk, bk, min_dist=2):
            continue
        board = _make_board(
            (wk, chess.Piece(chess.KING, chess.WHITE)),
            (bk, chess.Piece(chess.KING, chess.BLACK)),
            (wp, chess.Piece(chess.PAWN, chess.WHITE)),
        )
        if board is None:
            continue
        for b, t in _both_colors(board, "win"):
            positions.append((b, t))
            if len(positions) >= n:
                break
    return positions[:n]


def gen_kqkp(n):
    """KQKP: White has K+Q, Black has K+P. Theoretical win for White (to move)."""
    positions = []
    attempts = 0
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        wk = _random_square()
        bk = _random_square(exclude=[wk])
        if _kings_too_close(wk, bk, min_dist=2):
            continue
        wq = _random_square(exclude=[wk, bk])
        pawn_file = random.randint(0, 7)
        pawn_rank = random.randint(1, 5)
        bp = chess.square(pawn_file, pawn_rank)
        if bp in [wk, bk, wq]:
            continue
        board = _make_board(
            (wk, chess.Piece(chess.KING, chess.WHITE)),
            (bk, chess.Piece(chess.KING, chess.BLACK)),
            (wq, chess.Piece(chess.QUEEN, chess.WHITE)),
            (bp, chess.Piece(chess.PAWN, chess.BLACK)),
        )
        if board is None:
            continue
        for b, t in _both_colors(board, "win"):
            positions.append((b, t))
            if len(positions) >= n:
                break
    return positions[:n]


def gen_krkp(n):
    """KRKP: White has K+R, Black has K+P. Often a win, sometimes drawn.
    Labelled 'win'; OUTCOME_WEIGHTS handles drawn play-outs."""
    positions = []
    attempts = 0
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        wk = _random_square()
        bk = _random_square(exclude=[wk])
        if _kings_too_close(wk, bk, min_dist=2):
            continue
        wr = _random_square(exclude=[wk, bk])
        pawn_file = random.randint(0, 7)
        pawn_rank = random.randint(1, 5)
        bp = chess.square(pawn_file, pawn_rank)
        if bp in [wk, bk, wr]:
            continue
        board = _make_board(
            (wk, chess.Piece(chess.KING, chess.WHITE)),
            (bk, chess.Piece(chess.KING, chess.BLACK)),
            (wr, chess.Piece(chess.ROOK, chess.WHITE)),
            (bp, chess.Piece(chess.PAWN, chess.BLACK)),
        )
        if board is None:
            continue
        for b, t in _both_colors(board, "win"):
            positions.append((b, t))
            if len(positions) >= n:
                break
    return positions[:n]


def gen_kbbk(n):
    """KBBK: two bishops (opposite colors) vs lone king. Theoretical win."""
    positions = []
    attempts = 0
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        wk = _random_square()
        bk = _random_square(exclude=[wk])
        if _kings_too_close(wk, bk, min_dist=2):
            continue
        wb1 = _random_square(exclude=[wk, bk])
        wb2 = _random_square(exclude=[wk, bk, wb1])
        # Must be on opposite colors
        if (chess.square_rank(wb1) + chess.square_file(wb1)) % 2 == \
           (chess.square_rank(wb2) + chess.square_file(wb2)) % 2:
            continue
        board = _make_board(
            (wk, chess.Piece(chess.KING, chess.WHITE)),
            (bk, chess.Piece(chess.KING, chess.BLACK)),
            (wb1, chess.Piece(chess.BISHOP, chess.WHITE)),
            (wb2, chess.Piece(chess.BISHOP, chess.WHITE)),
        )
        if board is None:
            continue
        for b, t in _both_colors(board, "win"):
            positions.append((b, t))
            if len(positions) >= n:
                break
    return positions[:n]


def gen_kbnk(n):
    """KBNK: bishop + knight vs lone king. Theoretical win but complex."""
    positions = []
    attempts = 0
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        wk = _random_square()
        bk = _random_square(exclude=[wk])
        if _kings_too_close(wk, bk, min_dist=2):
            continue
        wb = _random_square(exclude=[wk, bk])
        wn = _random_square(exclude=[wk, bk, wb])
        board = _make_board(
            (wk, chess.Piece(chess.KING, chess.WHITE)),
            (bk, chess.Piece(chess.KING, chess.BLACK)),
            (wb, chess.Piece(chess.BISHOP, chess.WHITE)),
            (wn, chess.Piece(chess.KNIGHT, chess.WHITE)),
        )
        if board is None:
            continue
        for b, t in _both_colors(board, "win"):
            positions.append((b, t))
            if len(positions) >= n:
                break
    return positions[:n]


def gen_drawn_positions(n):
    """Theoretically drawn positions: KBK, KNK, KBKB same color.
    These teach the model to recognize draws and not play for a win."""
    positions = []
    attempts = 0
    generators = [_gen_kbk, _gen_knk, _gen_kbkb_same_color]
    while len(positions) < n and attempts < n * 20:
        attempts += 1
        result = random.choice(generators)()
        if result is not None:
            board, theoretical = result
            # Mirror half of drawn positions too for color balance
            if random.random() < 0.5:
                board = board.mirror()
            positions.append((board, theoretical))
    return positions[:n]


def _gen_kbk():
    wk = _random_square()
    bk = _random_square(exclude=[wk])
    if _kings_too_close(wk, bk, min_dist=2):
        return None
    wb = _random_square(exclude=[wk, bk])
    board = _make_board(
        (wk, chess.Piece(chess.KING, chess.WHITE)),
        (bk, chess.Piece(chess.KING, chess.BLACK)),
        (wb, chess.Piece(chess.BISHOP, chess.WHITE)),
    )
    return (board, "draw") if board else None


def _gen_knk():
    wk = _random_square()
    bk = _random_square(exclude=[wk])
    if _kings_too_close(wk, bk, min_dist=2):
        return None
    wn = _random_square(exclude=[wk, bk])
    board = _make_board(
        (wk, chess.Piece(chess.KING, chess.WHITE)),
        (bk, chess.Piece(chess.KING, chess.BLACK)),
        (wn, chess.Piece(chess.KNIGHT, chess.WHITE)),
    )
    return (board, "draw") if board else None


def _gen_kbkb_same_color():
    wk = _random_square()
    bk = _random_square(exclude=[wk])
    if _kings_too_close(wk, bk, min_dist=2):
        return None
    wb = _random_square(exclude=[wk, bk])
    wb_color = (chess.square_rank(wb) + chess.square_file(wb)) % 2
    candidates = [sq for sq in range(64)
                  if sq not in [wk, bk, wb]
                  and (chess.square_rank(sq) + chess.square_file(sq)) % 2 == wb_color]
    if not candidates:
        return None
    bb = random.choice(candidates)
    board = _make_board(
        (wk, chess.Piece(chess.KING, chess.WHITE)),
        (bk, chess.Piece(chess.KING, chess.BLACK)),
        (wb, chess.Piece(chess.BISHOP, chess.WHITE)),
        (bb, chess.Piece(chess.BISHOP, chess.BLACK)),
    )
    return (board, "draw") if board else None


# ---------------------------------------------------------------------------
# Stockfish binary detection
# ---------------------------------------------------------------------------

def _is_executable(path):
    if not os.path.isfile(path):
        return False
    st = os.stat(path)
    return bool(st.st_mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH))


def _candidate_score(filename):
    name = filename.lower()
    score = 0
    machine = platform.machine().lower()
    is_apple = "apple-silicon" in name or "m1" in name or "arm64" in name
    is_x86 = "x86-64" in name or "x86_64" in name
    if machine in ("arm64", "aarch64"):
        score += 100 if is_apple else (-50 if is_x86 else 0)
    else:
        score += 100 if is_x86 else (-100 if is_apple else 0)
    for feature, bonus in [("avx512", 40), ("vnni", 35), ("bmi2", 30),
                            ("avx2", 25), ("sse41-popcnt", 10), ("sse41", 5)]:
        if feature in name:
            score += bonus
            break
    if name == "stockfish":
        score += 15
    if name.endswith((".nnue", ".zip", ".tar")):
        score -= 1000
    return score


def find_stockfish_binary(stockfish_dir=None, explicit_path=None):
    if explicit_path:
        if not _is_executable(explicit_path):
            raise FileNotFoundError(f"--stockfish-path '{explicit_path}' not executable.")
        return explicit_path
    search_dir = stockfish_dir or "stockfish"
    if not os.path.isdir(search_dir):
        raise FileNotFoundError(f"Stockfish directory '{search_dir}' not found.")
    candidates = [p for p in glob.glob(os.path.join(search_dir, "**", "stockfish*"),
                                        recursive=True) if _is_executable(p)]
    if not candidates:
        raise FileNotFoundError(f"No executable stockfish binary under '{search_dir}'.")
    candidates.sort(key=_candidate_score, reverse=True)
    log.info(f"Auto-detected Stockfish binary: {candidates[0]}")
    return candidates[0]


# ---------------------------------------------------------------------------
# Play out one endgame position
# ---------------------------------------------------------------------------

def play_endgame(board_start, theoretical_outcome, sf_teacher, sf_player,
                 teacher_limit, player_limit, max_moves=100):
    """Play out a single endgame position with Stockfish on both sides.

    theoretical_outcome: "win" or "draw" from the SIDE TO MOVE's perspective
                         at the START of the position. This is the critical
                         difference from the old code which used White's perspective.

    Returns:
        examples: list of (state, policy_target, z, outcome_weight)
        actual_outcome: "win"/"draw"/"loss" from the STARTING side-to-move's perspective
    """
    board = board_start.copy()
    starting_color = board.turn  # remember who started -- outcome measured from their view
    raw_examples = []
    ply = 0

    while not board.is_game_over(claim_draw=True) and ply < max_moves:
        side_to_move = board.turn

        try:
            info = sf_teacher.analyse(board, teacher_limit)
            if not info.get("pv"):
                break
            teacher_move = info["pv"][0]
        except Exception as e:
            log.warning(f"Teacher analysis failed: {e}")
            break

        mirror = (side_to_move == chess.BLACK)
        policy_target = np.zeros(train.ACTION_SIZE, dtype=np.float32)
        policy_target[train.move_policy_index(teacher_move, mirror)] = 1.0
        state = train.board_to_tensor(board)
        raw_examples.append((state, policy_target, side_to_move))

        try:
            result = sf_player.play(board, player_limit)
            move = result.move
        except Exception as e:
            log.warning(f"Player move failed: {e}")
            break

        if move not in board.legal_moves:
            log.warning(f"Illegal move {move} at {board.fen()}")
            break
        board.push(move)
        ply += 1

    # Determine actual outcome from WHITE's perspective first
    if board.is_checkmate():
        winner_is_white = (board.turn == chess.BLACK)
        actual_z_white = 1.0 if winner_is_white else -1.0
    else:
        actual_z_white = 0.0  # draw or move limit

    # Convert to starting-side-to-move's perspective
    if starting_color == chess.WHITE:
        actual_z_stm = actual_z_white
    else:
        actual_z_stm = -actual_z_white

    if actual_z_stm > 0.5:
        actual_outcome = "win"
    elif actual_z_stm < -0.5:
        actual_outcome = "loss"
    else:
        actual_outcome = "draw"

    outcome_weight = OUTCOME_WEIGHTS.get((theoretical_outcome, actual_outcome), 0.0)

    # Build training examples -- z always from the PLY's side-to-move perspective
    examples = []
    for state, policy_target, side_to_move in raw_examples:
        z = actual_z_white if side_to_move == chess.WHITE else -actual_z_white
        z = float(np.clip(z, -1.0, 1.0))
        examples.append((state, policy_target, z, outcome_weight))

    return examples, actual_outcome


# ---------------------------------------------------------------------------
# Training step
# ---------------------------------------------------------------------------

def endgame_train_step(model, optimizer, batch, device,
                        value_loss_weight=2.0, label_smoothing=0.05):
    """One gradient step on a batch of endgame examples.

    Loss weight = BASE_WEIGHT + abs(outcome_weight).
    Penalty examples get high weight on a correctly-signed z target (already
    negative for losses), so the gradient pushes the value head in the right
    direction WITHOUT flipping the target.
    """
    states, policy_targets, zs, outcome_weights = zip(*batch)

    states_t  = torch.from_numpy(np.stack(states)).float().to(device)
    policy_t  = torch.from_numpy(np.stack(policy_targets)).float().to(device)
    z_t       = torch.tensor(zs, dtype=torch.float32).to(device)
    weights_t = torch.tensor([BASE_WEIGHT + abs(w) for w in outcome_weights],
                              dtype=torch.float32).to(device)
    weights_t = weights_t / (weights_t.mean() + 1e-8)

    logits, value = model(states_t)

    n_actions = logits.shape[1]
    smooth_policy = policy_t * (1.0 - label_smoothing) + label_smoothing / n_actions
    log_probs = F.log_softmax(logits, dim=1)
    policy_loss = (weights_t * -(smooth_policy * log_probs).sum(dim=1)).mean()

    value_loss = (weights_t * (value.squeeze(1) - z_t) ** 2).mean()

    loss = policy_loss + value_loss_weight * value_loss
    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
    optimizer.step()

    return policy_loss.item(), value_loss.item()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Supervised endgame training to fix value head conversion failures.")
    parser.add_argument("--model", type=str, default=train.BEST_MODEL_PATH)
    parser.add_argument("--output", type=str, default=None)
    parser.add_argument("--stockfish-dir", type=str, default="stockfish")
    parser.add_argument("--stockfish-path", type=str, default=None)
    parser.add_argument("--stockfish-threads", type=int, default=1)
    parser.add_argument("--stockfish-hash", type=int, default=16)
    parser.add_argument("--teacher-movetime-ms", type=int, default=50,
                        help="Movetime for teacher annotation per ply (default 50ms). "
                             "Simple endgames don't need more than 25-50ms.")
    parser.add_argument("--player-movetime-ms", type=int, default=20,
                        help="Movetime for Stockfish making actual moves (default 20ms).")
    parser.add_argument("--positions", type=int, default=1000,
                        help="Total endgame starting positions to generate (default 1000). "
                             "Each plays out to ~20-80 plies of training examples. "
                             "Half will be White-up, half Black-up automatically.")
    parser.add_argument("--max-moves", type=int, default=120,
                        help="Max plies per endgame before declaring draw (default 120).")
    parser.add_argument("--train-steps", type=int, default=50,
                        help="Gradient steps after collecting examples (default 50). "
                             "Keep low -- this is a surgical nudge, not a full retrain.")
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--lr", type=float, default=3e-4,
                        help="Learning rate (default 3e-4, lower than stockfish_train "
                             "to avoid overwriting existing knowledge).")
    parser.add_argument("--value-loss-weight", type=float, default=2.0,
                        help="Weight on value loss vs policy loss (default 2.0). "
                             "Higher than normal since the value head is the target.")
    parser.add_argument("--label-smoothing", type=float, default=0.05)
    parser.add_argument("--device", type=str, default="cpu",
                        choices=["cpu", "mps", "cuda"])
    parser.add_argument("--seed", type=int, default=42)
    # Endgame type fractions
    parser.add_argument("--kqk-frac",  type=float, default=0.25)
    parser.add_argument("--krk-frac",  type=float, default=0.20)
    parser.add_argument("--kpk-frac",  type=float, default=0.15)
    parser.add_argument("--kqkp-frac", type=float, default=0.10)
    parser.add_argument("--krkp-frac", type=float, default=0.10)
    parser.add_argument("--kbbk-frac", type=float, default=0.05)
    parser.add_argument("--kbnk-frac", type=float, default=0.05)
    parser.add_argument("--draw-frac", type=float, default=0.10)
    args = parser.parse_args()

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s [%(levelname)s] %(message)s",
                        datefmt="%H:%M:%S")

    output_path = args.output or args.model
    device = torch.device(args.device)

    model = train.DualHeadResNet().to(device)
    model.load_state_dict(torch.load(args.model, map_location=device))
    log.info(f"Loaded model from '{args.model}'.")
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)

    sf_path = find_stockfish_binary(args.stockfish_dir, args.stockfish_path)
    sf_teacher = chess.engine.SimpleEngine.popen_uci(sf_path)
    sf_teacher.configure({"Threads": args.stockfish_threads,
                           "Hash": args.stockfish_hash,
                           "UCI_LimitStrength": False})
    sf_player = chess.engine.SimpleEngine.popen_uci(sf_path)
    sf_player.configure({"Threads": args.stockfish_threads,
                          "Hash": args.stockfish_hash,
                          "UCI_LimitStrength": False})
    log.info(f"Started Stockfish: {sf_path}")

    teacher_limit = chess.engine.Limit(time=args.teacher_movetime_ms / 1000.0)
    player_limit  = chess.engine.Limit(time=args.player_movetime_ms / 1000.0)

    # Generate positions according to fractions
    n = args.positions
    fracs = {"kqk": args.kqk_frac, "krk": args.krk_frac, "kpk": args.kpk_frac,
             "kqkp": args.kqkp_frac, "krkp": args.krkp_frac,
             "kbbk": args.kbbk_frac, "kbnk": args.kbnk_frac, "draw": args.draw_frac}
    total_frac = sum(fracs.values())
    counts = {k: max(2, int(round(v / total_frac * n))) for k, v in fracs.items()}
    log.info(f"Generating {sum(counts.values())} positions (all 4 color/turn combos): {counts}")

    all_positions = []
    all_positions += gen_kqk(counts["kqk"])
    all_positions += gen_krk(counts["krk"])
    all_positions += gen_kpk(counts["kpk"])
    all_positions += gen_kqkp(counts["kqkp"])
    all_positions += gen_krkp(counts["krkp"])
    all_positions += gen_kbbk(counts["kbbk"])
    all_positions += gen_kbnk(counts["kbnk"])
    all_positions += gen_drawn_positions(counts["draw"])
    random.shuffle(all_positions)

    # Verify color balance
    white_to_move = sum(1 for b, _ in all_positions if b.turn == chess.WHITE)
    black_to_move = len(all_positions) - white_to_move
    log.info(f"Generated {len(all_positions)} positions: "
             f"{white_to_move} White-to-move, {black_to_move} Black-to-move.")

    # Play out all positions
    all_examples = []
    outcome_counts = {}
    weight_counts = {k: 0 for k in OUTCOME_WEIGHTS}

    try:
        for board, theoretical in tqdm(all_positions, desc="Playing endgames"):
            examples, actual = play_endgame(
                board, theoretical, sf_teacher, sf_player,
                teacher_limit, player_limit, args.max_moves)
            all_examples.extend(examples)
            outcome_counts[actual] = outcome_counts.get(actual, 0) + 1
            key = (theoretical, actual)
            weight_counts[key] = weight_counts.get(key, 0) + 1

        log.info(f"Collected {len(all_examples)} training examples.")
        log.info(f"Actual outcomes (from starting side-to-move): {outcome_counts}")
        log.info("Breakdown (theoretical -> actual): count  weight")
        for key, count in sorted(weight_counts.items()):
            w = OUTCOME_WEIGHTS.get(key, 0.0)
            log.info(f"  {key[0]:6s} -> {key[1]:6s}: {count:4d}  (weight {w:+.2f})")

        if len(all_examples) < args.batch_size:
            log.error(f"Only {len(all_examples)} examples, need at least {args.batch_size}. "
                      f"Increase --positions.")
            return

        # Check z distribution -- should be roughly balanced
        zs = [ex[2] for ex in all_examples]
        pos = sum(1 for z in zs if z > 0.5)
        neg = sum(1 for z in zs if z < -0.5)
        neu = len(zs) - pos - neg
        log.info(f"Value target distribution: +1={pos} ({pos/len(zs):.1%}), "
                 f"0={neu} ({neu/len(zs):.1%}), -1={neg} ({neg/len(zs):.1%})")
        if pos / len(zs) > 0.7 or neg / len(zs) > 0.7:
            log.warning("Value targets are heavily skewed! Color balance may be off. "
                        "Check position generation.")

        # Training
        model.train()
        log.info(f"Training for {args.train_steps} steps.")
        total_pl = total_vl = 0.0
        for step in tqdm(range(args.train_steps), desc="Training"):
            batch = random.sample(all_examples, min(args.batch_size, len(all_examples)))
            pl, vl = endgame_train_step(model, optimizer, batch, device,
                                         args.value_loss_weight, args.label_smoothing)
            total_pl += pl
            total_vl += vl
            if (step + 1) % 10 == 0:
                log.info(f"  step {step+1}/{args.train_steps}  "
                         f"policy_loss={pl:.4f}  value_loss={vl:.4f}")

        log.info(f"Done. avg policy_loss={total_pl/args.train_steps:.4f}  "
                 f"avg value_loss={total_vl/args.train_steps:.4f}")

        model.eval()
        torch.save(model.state_dict(), output_path)
        log.info(f"Saved to '{output_path}'. Run check_value_head.py before "
                 f"resuming stockfish_train.py.")

    finally:
        sf_teacher.quit()
        sf_player.quit()


if __name__ == "__main__":
    main()
